package com.usermanagement.model.processors;

import com.usermanagement.model.Team;
import lombok.RequiredArgsConstructor;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.server.RepresentationModelProcessor;
import org.springframework.stereotype.Component;

// Gets triggered when we use e.g. the EntityModel.of() in our TeamController.get()
// add aditionall Links (e.g. in addition to the links generated by Spring Data
@Component
public class TeamProcessor implements RepresentationModelProcessor<EntityModel<Team>> {

    @Override
    public EntityModel<Team> process(EntityModel<Team> model) {

        // remove automatic generated links if necessary
        /* model.removeLinks(); */

        // add our custom links

        return model;
    }

}
